[project]
name = "tailwind"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "openai>=1.52.0",
    "python-dotenv>=1.0.1",
    "streamlit-audiorecorder>=0.0.5",
    "streamlit>=1.39.0",
]
